name: Express Store Orders CI & CD

on:
  push:
    branches: [ dev-p1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./ExpressStoreOrders.sln
    - name: Build
      run: dotnet build ./ExpressStoreOrders.sln
    - name: Test
      run: dotnet test ./ExpressStoreOrders.sln